### ISSUE TITLE
IllegalStateException parsing APKs with no resource table. In AGP 7, android-test APKs will have no resource table if androidTest/res is empty

### ISSUE THREAD

**Issue by autonomousapps** [MightyCreak/diffuse#124]
In AGP 7, if you execute (e.g.)
```
./gradlew lib:assembleDebugAndroidTest
```
on an Android library project that doesn't have any resources (no `androidTest/res` directory), and then attempt to compare that APK with one built with AGP 4, you'll get an error like this:

```
$ diffuse diff --apk test4.apk test7.apk
Exception in thread "main" java.lang.IllegalStateException: ResourceTableChunk package count was < 1.
        at com.android.apksig.ApkSigner.checkState(ApkSigner.java:1)
        at com.google.devrel.gmscore.tools.apk.arsc.ResourceTableChunk.<init>(ResourceTableChunk.java:7)
        at com.google.devrel.gmscore.tools.apk.arsc.Chunk.newInstance(Chunk.java:57)
        at com.jakewharton.diffuse.Arsc$Companion.create(Arsc.kt:42)
        at com.jakewharton.diffuse.Apk$Companion.parse(Apk.kt:84)
        at com.jakewharton.diffuse.DiffCommand.run(diffuse.kt:117)
        at com.github.ajalt.clikt.parsers.Parser.parse(Parser.kt:5266)
        at com.github.ajalt.clikt.parsers.Parser.parse(Parser.kt:5274)
        at com.github.ajalt.clikt.core.CliktCommand.parse$default(CliktCommand.kt:281)
        at com.jakewharton.diffuse.Diffuse.main(diffuse.kt:23324)
```

Note that this issue arises regardless of whether the library project uses
```
android.buildFeatures.androidResources = false
```
That value appears to be ignored, at least in AGP 7.0.3. The mere presence of a resource in `androidrTest/res` can workaround this issue.

`apktool` has a similar issue when executing `apktool d path/to/apk -o foo`, but there's a [CLI option](https://github.com/iBotPeaches/Apktool/blob/master/brut.apktool/apktool-cli/src/main/java/brut/apktool/Main.java#L137), `-r`, that solves the problem: `apktool -r d path/to/apk -o foo`.

**Comment by MightyCreak** [comment]
I don't think this is related to diffuse... are you sure you've submitted an issue on the repository you wanted?

**Comment by autonomousapps** [comment]
oh dear god this is the wrong diffuse. I am SO sorry. (hope you get a laugh, though)

**Comment by MightyCreak** [comment]
Hahaha no worries :wink: 
You got me puzzled though :sweat_smile:

**Comment by autonomousapps** [comment]
in case you're curious about your github twin https://github.com/JakeWharton/diffuse/issues/104
