### ISSUE TITLE
Preferences cannot be saved in latest release (0.7.4)

### ISSUE THREAD

**Issue by uffejakobsen** [MightyCreak/diffuse#156]
Preferences cannot be saved in latest release (0.7.4)

Pressing "OK" button in Preferences gives the following error.

Seen on Archlinux official diffuse-0.7.4.-1 package

```
Traceback (most recent call last):
  File "/usr/share/diffuse/diffuse/main.py", line 1589, in preferences_cb
    if self.prefs.runDialog(self.get_toplevel()):
  File "/usr/share/diffuse/diffuse/preferences.py", line 280, in runDialog
    self.string_prefs[k] = utils.null_to_empty(widgets[k].get_text())
AttributeError: 'FontButton' object has no attribute 'get_text'. Did you mean: 'get_font'?
```

**Comment by MightyCreak** [comment]
I'll check that tomorrow, thank you!!
